In [2]:
import graphlab
from PIL import Image
import os
from random import shuffle # mixing up or currently ordered data that might lead our network astray in training.
import pandas as pd
# from sklearn import preprocessing
# from sklearn import svm
import graphlab
# import matplotlib.pyplot as plt
import numpy as np
import cv2

In [3]:
size = 128, 128
for img in os.listdir('E:/td/jeans'):
    DIR = 'E:/td/jeans' + '/'
    img  = DIR+str(img)
    im = Image.open(img)
    im.resize(size)
    #print(im.size)

In [4]:
url='E:/td/jeans'
data = graphlab.image_analysis.load_images(url)
data['label']='jeans'
graphlab.canvas.set_target('ipynb')
data.show()
data
#img.show()

This non-commercial license of GraphLab Create for academic use is assigned to vartikanarang.hcst.cs14@sgei.org and will expire on October 01, 2018.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\Ridhima\AppData\Local\Temp\graphlab_server_1524541671.log.0


Columns:
	path	str
	image	Image
	label	str

Rows: 766

Data:
+--------------------------------+------------------------+-------+
|              path              |         image          | label |
+--------------------------------+------------------------+-------+
|    E:/td/jeans/pic_339.jpg     | Height: 183 Width: 275 | jeans |
| E:/td/jeans/gpic_004 (64).jpg  | Height: 275 Width: 183 | jeans |
| E:/td/jeans/gpic_004 (94).jpg  | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_399.jpg     | Height: 225 Width: 225 | jeans |
|    E:/td/jeans/pic_305.jpg     | Height: 186 Width: 270 | jeans |
|    E:/td/jeans/pic_001.png     | Height: 88 Width: 240  | jeans |
|    E:/td/jeans/pic_019.jpg     | Height: 254 Width: 199 | jeans |
| E:/td/jeans/gpic_004 (236).jpg | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_290.jpg     | Height: 259 Width: 194 | jeans |
|    E:/td/jeans/pic_351.jpg     | Height: 225 Width: 225 | jeans |
+--------------------------------+------------------------+-------+
[766 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [5]:
url='E:/td/shirts'
data2 = graphlab.image_analysis.load_images(url)
data2['label']='shirts'
graphlab.canvas.set_target('ipynb')
data2.show()
data2
url='E:/td/tops'
data3 = graphlab.image_analysis.load_images(url)
data3['label']='tops'
graphlab.canvas.set_target('ipynb')
data3.show()
data3

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_167.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/bpic_007 (98).jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_363.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_184.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_295.jpg

Read 249 images in 5.00259 secs	speed: 49.7742 file/sec

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_090.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/ypic_001 (438).jpg

Read 534 images in 10.0269 secs	speed: 56.7238 file/sec

Unexpected JPEG decode failure	 file: E:/td/shirts/ypic_001 (206).jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_018.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/ypic_001 (450).jpg

Read 793 images in 15.0464 secs	speed: 51.5991 file/sec

Unexpected JPEG decode failure	 file: E:/td/shirts/ypic_001 (145).jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/bpic_007 (357).jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_010.jpg

Read 1048 images in 20.0553 secs	speed: 50.9094 file/sec

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_320.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_407.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/pic_345.jpg

Unexpected JPEG decode failure	 file: E:/td/shirts/bpic_007 (28).jpg

Unsupported PNG color type: 3	 file: E:/td/shirts/pic_001.png

Unexpected JPEG decode failure	 file: E:/td/shirts/ypic_001 (350).jpg

Read 1279 images in 25.0811 secs	speed: 45.9626 file/sec

Unsupported image format. Supported formats are JPG and PNG	 file: E:/td/tops/Photoshop_Set-Up.exe

Read 256 images in 6.06255 secs	speed: 42.2265 file/sec

Read 558 images in 11.0731 secs	speed: 60.2733 file/sec

Unsupported image format. Supported formats are JPG and PNG	 file: E:/td/tops/Kanika.m..pdf

Unexpected JPEG decode failure	 file: E:/td/tops/pic_504.jpg

Read 862 images in 16.1031 secs	speed: 60.4363 file/sec

Unsupported image format. Supported formats are JPG and PNG	 file: E:/td/tops/_d286e695551e7cf2e09aa2132c381811_Overfitting_Demo_Ridge_Lasso.ipynb.zip

Read 1125 images in 21.1186 secs	speed: 52.4375 file/sec

Columns:
	path	str
	image	Image
	label	str

Rows: 1278

Data:
+-------------------------------+------------------------+-------+
|              path             |         image          | label |
+-------------------------------+------------------------+-------+
| E:/td/tops/bpic_003 (418).jpg | Height: 259 Width: 194 |  tops |
| E:/td/tops/bpic_003 (212).jpg | Height: 225 Width: 225 |  tops |
| E:/td/tops/bpic_003 (462).jpg | Height: 225 Width: 225 |  tops |
|     E:/td/tops/pic_149.jpg    | Height: 259 Width: 194 |  tops |
| E:/td/tops/ypic_003 (163).jpg | Height: 225 Width: 225 |  tops |
| E:/td/tops/bpic_003 (269).jpg | Height: 275 Width: 183 |  tops |
| E:/td/tops/bpic_003 (473).jpg | Height: 224 Width: 224 |  tops |
|     E:/td/tops/pic_441.jpg    | Height: 262 Width: 192 |  tops |
|     E:/td/tops/pic_093.jpg    | Height: 259 Width: 194 |  tops |
| E:/td/tops/bpic_003 (357).jpg | Height: 284 Width: 177 |  tops |
+-------------------------------+------------------------+-------+
[1278 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [6]:
data = data.append(data2)
data = data.append(data3)

In [7]:
graphlab.canvas.set_target('ipynb')
data.show()
data

Columns:
	path	str
	image	Image
	label	str

Rows: 3426

Data:
+--------------------------------+------------------------+-------+
|              path              |         image          | label |
+--------------------------------+------------------------+-------+
|    E:/td/jeans/pic_339.jpg     | Height: 183 Width: 275 | jeans |
| E:/td/jeans/gpic_004 (64).jpg  | Height: 275 Width: 183 | jeans |
| E:/td/jeans/gpic_004 (94).jpg  | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_399.jpg     | Height: 225 Width: 225 | jeans |
|    E:/td/jeans/pic_305.jpg     | Height: 186 Width: 270 | jeans |
|    E:/td/jeans/pic_001.png     | Height: 88 Width: 240  | jeans |
|    E:/td/jeans/pic_019.jpg     | Height: 254 Width: 199 | jeans |
| E:/td/jeans/gpic_004 (236).jpg | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_290.jpg     | Height: 259 Width: 194 | jeans |
|    E:/td/jeans/pic_351.jpg     | Height: 225 Width: 225 | jeans |
+--------------------------------+------------------------+-------+
[3426 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [107]:
# labels = data['label'].unique()
# le = preprocessing.LabelEncoder()
# le.fit(list(labels))
# print(le.transform(data['label']))

In [17]:
extractor = graphlab.feature_engineering.DeepFeatureExtractor(features = 'image',
                                                        model='auto')

Downloading https://static.turi.com/products/graphlab-create/resources/models/python2.7/imagenet_model_iter45/objects.bin to C:/Users/Ridhima/AppData/Local/Temp/graphlab-Ridhima/560/038ecc1b-72f3-4626-9bd1-3b282b08328e.bin

In [18]:
extractor = extractor.fit(data)

In [19]:
extracted_model = extractor['model']

In [20]:
features_sf = extractor.transform(data)

Images being resized.

In [21]:
print features_sf
print features_sf['deep_features.image'][0]

+--------------------------------+------------------------+-------+
|              path              |         image          | label |
+--------------------------------+------------------------+-------+
|    E:/td/jeans/pic_339.jpg     | Height: 183 Width: 275 | jeans |
| E:/td/jeans/gpic_004 (64).jpg  | Height: 275 Width: 183 | jeans |
| E:/td/jeans/gpic_004 (94).jpg  | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_399.jpg     | Height: 225 Width: 225 | jeans |
|    E:/td/jeans/pic_305.jpg     | Height: 186 Width: 270 | jeans |
|    E:/td/jeans/pic_001.png     | Height: 88 Width: 240  | jeans |
|    E:/td/jeans/pic_019.jpg     | Height: 254 Width: 199 | jeans |
| E:/td/jeans/gpic_004 (236).jpg | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_290.jpg     | Height: 259 Width: 194 | jeans |
|    E:/td/jeans/pic_351.jpg     | Height: 225 Width: 225 | jeans |
+--------------------------------+------------------------+-------+
+-------------------------------+
|      deep_fe

In [27]:
train, test = features_sf.random_split(0.5, seed=1)



## logistic classifier for supervised learning
model = graphlab.logistic_classifier.create(train, target='label',
                              features =  ['deep_features.image'])
print(model.predict(test))

## svm classifier for supervised learning
x = np.array(train['deep_features.image'])
y = np.array(train['label'])
clf = svm.SVC(gamma=0.000001, C=100,kernel='rbf')
clf.fit(x,y)

print clf.predict(np.array(test['deep_features.image']))
print np.array(test['label'])
clf.score(np.array(test['deep_features.image']),np.array(test['label']))
#knn_model = graphlab.nearest_neighbors.create(data)
#knn_model = graphlab.nearest_neighbors.create(data,features=['deep_features.image'],
   #                                          label='label')


PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.



WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.

Logistic regression:

--------------------------------------------------------

Number of examples          : 1662

Number of classes           : 3

Number of feature columns   : 1

Number of unpacked features : 4096

Number of coefficients    : 8194

Starting L-BFGS

--------------------------------------------------------

+-----------+----------+-----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy | Validation-accuracy |

+-----------+----------+-----------+--------------+-------------------+---------------------+

| 1         | 6        | 0.000040  | 1.538526     | 0.650421          | 0.626506            |

| 2         | 8        | 1.000000  | 2.248936     | 0.801444          | 0.783133            |

| 3         | 9        | 1.000000  | 2.659768     | 0.824910          | 0.795181            |

| 4         | 10       | 1.000000  | 3.086746     | 0.867629          | 0.843373            |

| 5         | 11       | 1.000000  | 3.487674     | 0.833333          | 0.734940            |

| 6         | 13       | 1.000000  | 4.144763     | 0.875451          | 0.819277            |

| 10        | 17       | 1.000000  | 5.727390     | 0.936823          | 0.855422            |

+-----------+----------+-----------+--------------+-------------------+---------------------+

TERMINATED: Iteration limit reached.

This model may not be optimal. To improve it, consider increasing `max_iterations`.

['jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'shirts', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'shirts', 'jeans', 'jeans', 'shirts', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'tops', 'shirts', 'jeans', 'shirts', 'jeans', 'jeans', 'tops', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'tops', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'tops', 'jeans', 'jeans', 'tops', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'jeans', 'shirts', 'shirts', ... ]
['jeans' 'jeans' 'jeans' ..., 'tops' 'tops' 'tops']
['jeans' 'jeans' 'jeans' ..., 'tops' 't

0.85450208706022657

In [31]:
print(y)
print(test)
test['predicted_label'] = clf.predict(np.array(test['deep_features.image']))
print(test)

['jeans' 'jeans' 'jeans' ..., 'tops' 'tops' 'tops']
+--------------------------------+------------------------+-------+
|              path              |         image          | label |
+--------------------------------+------------------------+-------+
|    E:/td/jeans/pic_339.jpg     | Height: 183 Width: 275 | jeans |
| E:/td/jeans/gpic_004 (64).jpg  | Height: 275 Width: 183 | jeans |
| E:/td/jeans/gpic_004 (94).jpg  | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_305.jpg     | Height: 186 Width: 270 | jeans |
|    E:/td/jeans/pic_019.jpg     | Height: 254 Width: 199 | jeans |
| E:/td/jeans/gpic_004 (236).jpg | Height: 275 Width: 183 | jeans |
|    E:/td/jeans/pic_290.jpg     | Height: 259 Width: 194 | jeans |
|    E:/td/jeans/pic_351.jpg     | Height: 225 Width: 225 | jeans |
|    E:/td/jeans/pic_047.jpg     | Height: 259 Width: 194 | jeans |
| E:/td/jeans/gpic_004 (320).jpg | Height: 176 Width: 286 | jeans |
+--------------------------------+------------------------+-----

In [125]:
print(data['path'])

['E:/td/jeans/pic_072.jpg', 'E:/td/jeans/pic_350.jpg', 'E:/td/jeans/pic_019.jpg', 'E:/td/jeans/pic_102.jpg', 'E:/td/jeans/gpic_004 (121).jpg', 'E:/td/jeans/gpic_004 (317).jpg', 'E:/td/jeans/gpic_004 (18).jpg', 'E:/td/jeans/pic_207.jpg', 'E:/td/jeans/pic_060.jpg', 'E:/td/jeans/gpic_004 (4).jpg', 'E:/td/jeans/gpic_004 (122).jpg', 'E:/td/jeans/gpic_004 (192).jpg', 'E:/td/jeans/gpic_004 (222).jpg', 'E:/td/jeans/pic_080.jpg', 'E:/td/jeans/pic_272.jpg', 'E:/td/jeans/pic_200.jpg', 'E:/td/jeans/gpic_004 (319).jpg', 'E:/td/jeans/pic_282.jpg', 'E:/td/jeans/gpic_004 (160).jpg', 'E:/td/jeans/pic_235.jpg', 'E:/td/jeans/gpic_004 (283).jpg', 'E:/td/jeans/gpic_004 (130).jpg', 'E:/td/jeans/pic_194.jpg', 'E:/td/jeans/pic_271.jpg', 'E:/td/jeans/pic_262.jpg', 'E:/td/jeans/gpic_004 (166).jpg', 'E:/td/jeans/gpic_004 (135).jpg', 'E:/td/jeans/gpic_004 (284).jpg', 'E:/td/jeans/pic_270.jpg', 'E:/td/jeans/gpic_004 (252).jpg', 'E:/td/jeans/pic_126.jpg', 'E:/td/jeans/pic_221.jpg', 'E:/td/jeans/gpic_004 (26).jpg', 

In [108]:
# print(data[(data['path']=='E:/td/jeans/gpic_004 (64).jpg'))
data['new_col'] = data['path'].apply(lambda x: 'd' if x == 'E:/td/jeans/pic_027.jpg' else 'xn')
print(data)

+--------------------------------+------------------------+-------+---------+
|              path              |         image          | label | new_col |
+--------------------------------+------------------------+-------+---------+
|    E:/td/jeans/pic_027.jpg     | Height: 251 Width: 201 | jeans |    d    |
|    E:/td/jeans/pic_062.jpg     | Height: 184 Width: 275 | jeans |    xn   |
| E:/td/jeans/gpic_004 (91).jpg  | Height: 278 Width: 181 | jeans |    xn   |
|    E:/td/jeans/pic_403.jpg     | Height: 254 Width: 199 | jeans |    xn   |
|    E:/td/jeans/pic_186.jpg     | Height: 259 Width: 194 | jeans |    xn   |
| E:/td/jeans/gpic_004 (300).jpg | Height: 278 Width: 181 | jeans |    xn   |
| E:/td/jeans/gpic_004 (199).jpg | Height: 259 Width: 194 | jeans |    xn   |
|    E:/td/jeans/pic_201.jpg     | Height: 235 Width: 215 | jeans |    xn   |
| E:/td/jeans/gpic_004 (141).jpg | Height: 245 Width: 206 | jeans |    xn   |
| E:/td/jeans/gpic_004 (160).jpg | Height: 259 Width: 194 | jean

In [12]:
#image = cv2.imread("C:/Users/Ridhima/Desktop/bluetop.jpg")
#image = cv2.imread("G:/img-002/img/2-in-1_Space_Dye_Athletic_Tank/color_detection_blue_version.jpg")
def mdc(color):
    import cv2
    TRAIN_DATA = "G:/img-002/img/training data"
    #data = test[test['label'] == 'tops']
    l = []
    if color == 'red':
        for im in os.listdir(TRAIN_DATA):
            path = str(TRAIN_DATA)+"/"+str(im)
            new_path = 'E:/td/tops'+"/"+str(im)
            #print(path)
            image = cv2.imread(path)
            mask = cv2.inRange(image,np.array([17, 15, 100]) , np.array([50, 56, 200]))
            output = cv2.bitwise_and(image, image, mask = mask)
                #print output
            v = cv2.countNonZero(mask)
                #print(v)
            if v>200:
                l.append(new_path)
                    #cv2.imshow("images", ))
                cv2.waitKey(0)
        for e in l:
            print("'"+str(e)+"'")
            data['color1'] = data['path'].apply(lambda x: color if x == "'"+str(e)+"'" else 'xn')

    print(data.print_rows(num_rows=3426,num_columns=6))
        

mdc('red')


error: C:\projects\opencv-python\opencv\modules\core\src\arithm.cpp:1769: error: (-209) The lower boundary is neither an array of the same size and same type as src, nor a scalar in function cv::inRange


[0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L]


47

In [44]:
 #predictions = model.predict(test)
knn_model = graphlab.nearest_neighbors.create(features_sf, features=['deep_features.image'] , label='label')

Starting brute force nearest neighbors model training.

In [45]:
# knn = knn_model.query(features_sf[:1], k=5)
# #graphlab.canvas.set_target('ipynb')
# print knn

graphlab.canvas.set_target('ipynb')

In [46]:
#def get_images_from_ids(query_result):
#    return data.filter_by(query_result['reference_label'],'label')

def get_images_from_ids(query_result):
    return features_sf.filter_by(query_result['reference_label'],'label')

In [47]:
print len(features_sf)
jumpsuit = features_sf[60:61]
jumpsuit['image'].show()
print jumpsuit['label']

get_images_from_ids(knn_model.query(jumpsuit))['image'].show()

96


[1L]


Starting pairwise querying.

+--------------+---------+-------------+--------------+

| Query points | # Pairs | % Complete. | Elapsed Time |

+--------------+---------+-------------+--------------+

| 0            | 1       | 1.04167     | 33.671ms     |

| Done         |         | 100         | 41.578ms     |

+--------------+---------+-------------+--------------+

In [ ]:
# knn_model.query(jumpsuit,k=1)['image'].show()
# #knn_model.query(jumpsuit,k=1)

In [164]:
# sim_graph =knn_model.similarity_graph(k=3)
# sim_graph.show(vlabel='id', arrows=True)

AttributeError: 'NearestNeighborClassifier' object has no attribute 'similarity_graph'

In [ ]:
#image = cv2.imread("C:/Users/Ridhima/Desktop/bluetop.jpg")
#image = cv2.imread("G:/img-002/img/2-in-1_Space_Dye_Athletic_Tank/color_detection_blue_version.jpg")
TRAIN_DATA = "G:/img-002/img/training data"
for im in os.listdir(TRAIN_DATA):
    path = str(TRAIN_DATA)+"/"+str(im)
    #print(path)
    image = cv2.imread(path)
    mask = cv2.inRange(image,np.array([17, 15, 100]) , np.array([50, 56, 200]))
    output = cv2.bitwise_and(image, image, mask = mask)
    print output
    v = cv2.countNonZero(mask)
    print(v)
    if v>200:
        cv2.imshow("images", np.hstack([image,output]))
        cv2.waitKey(0)
    

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
0
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
321


In [3]:
# image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
# import matplotlib.pyplot as plt
# from sklearn.cluster import KMeans
# plt.figure()
# plt.axis("off")
# plt.imshow(image)

In [4]:
# from sklearn.cluster import KMeans
# image = image.reshape((image.shape[0] * image.shape[1], 3))
# clt = KMeans(n_clusters = 3)
# clt.fit(image)

In [ ]:
import numpy as np
boundaries = [
([17, 15, 100], [50, 56, 200]),
([86, 31, 4], [220, 88, 50]),
([25, 146, 190], [62, 174, 250]),
([103, 86, 65], [145, 133, 128])
]
mask = cv2.inRange(image,np.array([17, 15, 100]) , np.array([50, 56, 200]))
output = cv2.bitwise_and(image, image, mask = mask)
print output
v = cv2.countNonZero(mask)
print(v)
cv2.imshow("images", np.hstack([image, output]))
cv2.waitKey(0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
0


In [ ]:
for (lower, upper) in boundaries:
    # create NumPy arrays from the boundaries
    lower = np.array(lower, dtype = "uint8")
    upper = np.array(upper, dtype = "uint8")

    # find the colors within the specified boundaries and apply
    # the mask
    mask = cv2.inRange(image, lower, upper)
    output = cv2.bitwise_and(image, image, mask = mask)

    # show the images
    cv2.imshow("images", np.hstack([image, output]))
    cv2.waitKey(0)


In [ ]:
# Convert to HSV colorspace
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Define color range for masking
lower = n.array([0,100,100])
upper = n.array([20,255,255])

# Apply the mask
mask = cv2.inRange(hsv, lower, upper)

    #(source, destination, mask to apply)
result = cv2.bitwise_and(image,image, mask=mask)

In [90]:
print(data)

+--------------------------------+------------------------+-------+-------+
|              path              |         image          | label | color |
+--------------------------------+------------------------+-------+-------+
|    E:/td/jeans/pic_213.jpg     | Height: 194 Width: 259 | jeans |  blue |
|    E:/td/jeans/pic_341.jpg     | Height: 225 Width: 225 | jeans |  blue |
|    E:/td/jeans/pic_311.jpg     | Height: 225 Width: 225 | jeans |  blue |
|    E:/td/jeans/pic_104.jpg     | Height: 215 Width: 90  | jeans |  blue |
| E:/td/jeans/gpic_004 (105).jpg | Height: 275 Width: 183 | jeans |  blue |
|    E:/td/jeans/pic_019.jpg     | Height: 254 Width: 199 | jeans |  blue |
|    E:/td/jeans/pic_304.jpg     | Height: 251 Width: 201 | jeans |  blue |
|    E:/td/jeans/pic_108.jpg     | Height: 294 Width: 171 | jeans |  blue |
| E:/td/jeans/gpic_004 (254).jpg | Height: 275 Width: 183 | jeans |  blue |
|    E:/td/jeans/pic_407.jpg     | Height: 254 Width: 199 | jeans |  blue |
+-----------